export const GET_COURSES_REQUEST = 'GET_COURSES_REQUEST';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_FAILURE = 'GET_COURSES_FAILURE';

export const GET_MOVIEDETAIL_REQUEST = 'GET_MOVIEDETAIL_REQUEST';
export const GET_MOVIEDETAIL_SUCCESS = 'GET_MOVIEDETAIL_SUCCESS';
export const GET_MOVIEDETAIL_FAILURE = 'GET_MOVIEDETAIL_FAILURE';