export const THONG_TIN_LICH_CHIEU_PHIM_REQUESTS = "THONG_TIN_LICH_CHIEU_PHIM_REQUESTS";
export const THONG_TIN_LICH_CHIEU_PHIM_SUCCESS = "THONG_TIN_LICH_CHIEU_PHIM_SUCCESS";
export const THONG_TIN_LICH_CHIEU_PHIM_FAILURE = "THONG_TIN_LICH_CHIEU_PHIM_FAILURE";
