// Hệ thống
export const GET_HETHONGRAP_REQUEST = 'GET_HETHONGRAP_REQUEST';
export const GET_HETHONGRAP_SUCCESS = 'GET_HETHONGRAP_SUCCESS';
export const GET_HETHONGRAP_FAILURE = 'GET_HETHONGRAP_FAILURE';
// Lịch chiếu hệ thống rạp
export const GET_LICHCHIEUHTRAP_REQUEST = 'GET_LICHCHIEUHTRAP_REQUEST';
export const GET_LICHCHIEUHTRAP_SUCCESS = 'GET_LICHCHIEUHTRAP_SUCCESS';
export const GET_LICHCHIEUHTRAP_FAILURE = 'GET_LICHCHIEUHTRAP_FAILURE';
// Cụm rạp theo hệ thốngLICHCHIEUHTRAP
export const GET_CUMRAPHTRAP_REQUEST = 'GET_CUMRAPHTRAP_REQUEST';
export const GET_CUMRAPHTRAP_SUCCESS = 'GET_CUMRAPHTRAP_SUCCESS';
export const GET_CUMRAPHTRAP_FAILURE = 'GET_CUMRAPHTRAP_FAILURE';
//Lịch chiếu phim hệ thống rạp
export const GET_LTCHIEUHTRAP_REQUEST = 'GET_LTCHIEUHTRAP_REQUEST';
export const GET_LTCHIEUHTRAP_SUCCESS = 'GET_LTCHIEUHTRAP_SUCCESS';
export const GET_LTCHIEUHTRAP_FAILURE = 'GET_LTCHIEUHTRAP_FAILURE';


