export const GET_QUANLYRAP_REQUEST = 'GET_QUANLYRAP_REQUEST';
export const GET_QUANLYRAP_SUCCESS = 'GET_QUANLYRAP_SUCCESS';
export const GET_QUANLYRAP_FAILURE = 'GET_QUANLYRAP_FAILURE';
export const CHANGE_MA_HE_THONG = 'CHANGE_MA_HE_THONG';